products = [
    {
        '_id': '1',
        'name': 'Test 1',
        'image': '/images/test1.jpg',
        'description':
            'The media presents and implements evident, mechanic approximations only as a different and evasive distance.',
        'brand': 'Painting',
        'category': 'Painting',
        'price' : 8900,
        'countInStock' : 1,
        'rating' : 4.9,
        'numReviews': 12,
    },
    {
        '_id': '2',
        'name': 'Test 2',
        'image': '/images/test2.jpg',
        'description':
            'The aloof territorry depicts and verbalises the resonance to socialise, while the boundary of ergonomic tokens democratises and deconstructs the kontextkunst.',
        'brand': 'Pin',
        'category': 'Pin',
        'price' : 8000,
        'countInStock' : 0,
        'rating' : 4.4,
        'numReviews': 11,
    },
    {
        '_id': '3',
        'name': 'Test 3',
        'image': '/images/test3.jpg',
        'description':
            'The recognisable, exemplary conservator meta-textually and sub-textually extends the journal to convergences.',
        'brand': 'Photo',
        'category': 'Photo',
        'price' : 800,
        'countInStock' : 16,
        'rating' : 3.7,
        'numReviews': 2,
    },
    {
        '_id': '4',
        'name': 'Test 4',
        'image': '/images/test4.jpg',
        'description':
            'The ability to conceptualise harmonises and maps the temporary and socio-political art scene.',
        'brand': 'Painting',
        'category': 'Painting',
        'price' : 9000,
        'countInStock' : 1,
        'rating' : 4.4,
        'numReviews': 2,
    },
    {
        '_id': '5',
        'name': 'Test 5',
        'image': '/images/test5.jpg',
        'description':
            'This verbal and cybernetic analysis fabricates and oscillates an array of facets culminated by the peripheral, current display.',
        'brand': 'Pin',
        'category': 'Pin',
        'price' : 300,
        'countInStock' : 18,
        'rating' : 4.9,
        'numReviews': 16,
    },
]
