export const BIDDING_LIST_REQUEST = 'BIDDING_LIST_REQUEST'
export const BIDDING_LIST_SUCCESS = 'BIDDING_LIST_SUCCESS'
export const BIDDING_LIST_FAIL = 'BIDDING_LIST_FAIL'

export const BIDDING_DETAILS_REQUEST = 'BIDDING_DETAILS_REQUEST'
export const BIDDING_DETAILS_SUCCESS = 'BIDDING_DETAILS_SUCCESS'
export const BIDDING_DETAILS_FAIL = 'BIDDING_DETAILS_FAIL'

export const BIDDING_DELETE_REQUEST = 'BIDDING_DELETE_REQUEST'
export const BIDDING_DELETE_SUCCESS = 'BIDDING_DELETE_SUCCESS'
export const BIDDING_DELETE_FAIL = 'BIDDING_DELETE_FAIL'

export const BIDDING_CREATE_REQUEST = 'BIDDING_CREATE_REQUEST'
export const BIDDING_CREATE_SUCCESS = 'BIDDING_CREATE_SUCCESS'
export const BIDDING_CREATE_FAIL = 'BIDDING_CREATE_FAIL'
export const BIDDING_CREATE_RESET = 'BIDDING_CREATE_RESET'

export const BIDDING_UPDATE_REQUEST = 'BIDDING_UPDATE_REQUEST'
export const BIDDING_UPDATE_SUCCESS = 'BIDDING_UPDATE_SUCCESS'
export const BIDDING_UPDATE_FAIL = 'BIDDING_UPDATE_FAIL'
export const BIDDING_UPDATE_RESET = 'BIDDING_UPDATE_RESET'

export const BIDDING_TOP_REQUEST = 'BIDDING_TOP_REQUEST'
export const BIDDING_TOP_SUCCESS = 'BIDDING_TOP_SUCCESS'
export const BIDDING_TOP_FAIL = 'BIDDING_TOP_FAIL'

export const PRODUCT_CREATE_BID_REQUEST = 'PRODUCT_CREATE_BID_REQUEST'
export const PRODUCT_CREATE_BID_SUCCESS = 'PRODUCT_CREATE_BID_SUCCESS'
export const PRODUCT_CREATE_BID_FAIL = 'PRODUCT_CREATE_BID_FAIL'
export const PRODUCT_CREATE_BID_RESET = 'PRODUCT_CREATE_BID_RESET'