# Generated by Django 4.1.5 on 2023-03-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0005_review_createdat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="/placeholder.png", null=True, upload_to=""
                    ),
                ),
                ("event_description", models.TextField()),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=200)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BiddingProduct",
            fields=[
                ("bidding_name", models.CharField(max_length=100)),
                ("bidding_description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="/placeholder.png", null=True, upload_to=""
                    ),
                ),
                ("minimum_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("end_time", models.DateTimeField()),
                ("numBids", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "highest_bidder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bids_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bidding_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="base.biddingproduct",
                    ),
                ),
            ],
        ),
    ]
